name: release

on:
  push:
    branches: [master, main]
    tags: ["*"]

concurrency: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Get next release version (dry run)
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"
      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"
      - name: Build
        run: |
          dotnet publish -c Release -r linux-x64 -o ./release/linux DotNetAstGen/DotNetAstGen.csproj
          dotnet publish -c Release -r linux-arm -o ./release/linux-arm DotNetAstGen/DotNetAstGen.csproj
          dotnet publish -c Release -r osx-x64 -o ./release/macos DotNetAstGen/DotNetAstGen.csproj
          dotnet publish -c Release -r osx-arm64 -o ./release/macos-arm DotNetAstGen/DotNetAstGen.csproj
          dotnet publish -c Release -r win-x64 -o ./release/win DotNetAstGen/DotNetAstGen.csproj
          dotnet publish -c Release -r win-arm -o ./release/win-arm DotNetAstGen/DotNetAstGen.csproj
      - name: Rename
        run: |
          mv ./release/linux/DotNetAstGen dotnetastgen-linux
          mv ./release/linux-arm/DotNetAstGen dotnetastgen-linux-arm
          mv ./release/macos/DotNetAstGen dotnetastgen-macos
          mv ./release/macos-arm/DotNetAstGen dotnetastgen-macos-arm
          mv ./release/win/DotNetAstGen.exe dotnetastgen-win.exe
          mv ./release/win-arm/DotNetAstGen.exe dotnetastgen-win-arm.exe
      - name: Make executable
        run: |
          chmod +x dotnetastgen-linux
          chmod +x dotnetastgen-linux-arm
          chmod +x dotnetastgen-macos
          chmod +x dotnetastgen-macos-arm
      - name: Compress all executables
        run: |
          zip dotnetastgen-linux.zip dotnetastgen-linux
          zip dotnetastgen-linux-arm.zip  dotnetastgen-linux-arm
          zip dotnetastgen-macos.zip  dotnetastgen-macos
          zip dotnetastgen-macos-arm.zip  dotnetastgen-macos-arm
          zip dotnetastgen-win.zip dotnetastgen-win.exe
          zip dotnetastgen-win-arm.zip dotnetastgen-win-arm.exe
      - name: Set next release version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
          files: |
            dotnetastgen-linux.zip
            dotnetastgen-linux-arm.zip
            dotnetastgen-macos.zip
            dotnetastgen-macos-arm.zip
            dotnetastgen-win.exe.zip
            dotnetastgen-win-arm.exe.zip